poligonotiro/Controllers/LineaTiroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using poligonotiro.Models;
using poligonotiro.Models.ViewModels;

namespace poligonotiro.Controllers
{
    [Authorize]
    public class LineaTiroController : Controller
    {
        // GET: LineaTiro
        public ActionResult Index()
        {
            int varrol = MySession.Current.Rol;

            if (varrol == 2)
            {
                return Redirect("~/Profile/");
            }
            else
            {
                List<ListaLineaTiro> lst;
                using (Context db = new Context())
                {
                    lst = (from d in db.Linea_tiro
                           select new ListaLineaTiro
                           {
                               Idlineatiro = d.id_linea_tiro,
                               nombre = d.nombre_linea_tiro,


                               costopack = (decimal)d.costo_pack

                           }).ToList();
                }

                return View(lst);
            }

        }


        public ActionResult Nuevo()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Nuevo(ListaLineaTiro model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (Context db = new Context())
                    {
                        var oLineaTiro = new linea_tiro();
                        oLineaTiro.nombre_linea_tiro = model.nombre;
                        oLineaTiro.costo_pack = model.costopack;


                        db.Linea_tiro.Add(oLineaTiro);
                        db.SaveChanges();
                    }
                    return Redirect("~/LineaTiro/");
                }
                return View(model);
                //return Redirect("/Rol");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }



        public ActionResult Editar(int Idlineatiro)
        {
            ListaLineaTiro model = new ListaLineaTiro();

            using (Context db = new Context())
            {
                var oLineaTiro = db.Linea_tiro.Find(Idlineatiro);
                model.nombre = oLineaTiro.nombre_linea_tiro;
                model.costopack = (decimal)oLineaTiro.costo_pack;

            }
            return View(model);
        }


        [HttpPost]
        public ActionResult Editar(ListaLineaTiro model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (Context db = new Context())
                    {
                        var oLineaTiro = db.Linea_tiro.Find(model.Idlineatiro);
                        oLineaTiro.nombre_linea_tiro = model.nombre;
                        oLineaTiro.costo_pack = model.costopack;


                        db.Entry(oLineaTiro).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return Redirect("~/LineaTiro/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int idlineatiro)
        {
            using (Context db = new Context())
            {
                var oLineaTiro = db.Linea_tiro.Find(idlineatiro);
                db.Linea_tiro.Remove(oLineaTiro);
                db.SaveChanges();
            }
            return Redirect("~/LineaTiro/");
        }
    }
}

poligonotiro/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace poligonotiro.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult Index()
        {
            return View();
        }
    }
}

poligonotiro/Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using poligonotiro.Models;
using poligonotiro.Models.ViewModels;

namespace poligonotiro.Controllers
{
    [Authorize]
    public class ReservasController : Controller
    {
        // GET: Reservas
        public ActionResult Index()
        {
            int varrol = MySession.Current.Rol;

            if (varrol == 2)
            {
                return Redirect("~/Profile/");
            }
            else
            {
                List<Listareservaweb> lst;
                using (Context db = new Context())
                {
                    lst = (from d in db.Reserva_web
                           join t in db.Usuario on d.id_usuario equals t.id_usuario
                           join l in db.Linea_tiro on d.id_linea_tiro equals l.id_linea_tiro
                           select new Listareservaweb
                           {
                               Id = d.id_reserva_web,
                               idusuario = d.id_usuario,
                               fecha = d.fecha,
                               horainicio = d.hora_inicio,
                               cantidadminutos = d.cantidad_minutos,
                               horafin = d.hora_fin,
                               costo = (int)d.costo,
                               idlineatiro = d.id_linea_tiro,
                               nombreusuario = t.nombre_usuario,
                               costopack = (int)l.costo_pack,
                               nombrelinea = l.nombre_linea_tiro
                           }).ToList();
                }


                //DROPDOWN DE LINEAS DE TIRO

                List<ListaLineaTiro> lst1;
                using (Context db1 = new Context())
                {
                    lst1 = (from d1 in db1.Linea_tiro
                            select new ListaLineaTiro
                            {
                                Idlineatiro = d1.id_linea_tiro,
                                nombre = d1.nombre_linea_tiro
                            }).ToList();
                }

                List<SelectListItem> items = lst1.ConvertAll(d1 =>
                {
                    return new SelectListItem()
                    {
                        Text = d1.nombre.ToString(),
                        Value = d1.Idlineatiro.ToString(),
                        Selected = false
                    };
                });

                ViewBag.items = items;



                //DROPDOWN DE COSTOS DE PACK


                List<ListaLineaTiro> lst2;
                using (Context db1 = new Context())
                {
                    lst2 = (from d1 in db1.Linea_tiro
                            select new ListaLineaTiro
                            {
                                Idlineatiro = d1.id_linea_tiro,
                                costopack = (decimal)d1.costo_pack
                            }).ToList();
                }

                List<SelectListItem> items1 = lst2.ConvertAll(d2 =>
                {
                    return new SelectListItem()
                    {
                        Text = d2.costopack.ToString(),
                        Value = d2.costopack.ToString(),
                        Selected = false
                    };
                });

                ViewBag.items1 = items1;



                return View(lst);
            }
        }


        public ActionResult Nuevo()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Nuevo(Listareservaweb model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (Context db = new Context())
                    {
                        var oReserva = new reserva_web();
                        oReserva.id_usuario = (int)Session["IDUSUARIO"];
                        oReserva.fecha = model.fecha;
                        oReserva.hora_inicio = model.horainicio;
                        oReserva.cantidad_minutos = model.cantidadminutos;
                        oReserva.hora_fin = model.horafin;
                        oReserva.costo = model.costo;
                        oReserva.id_linea_tiro = model.idlineatiro;

                        db.Reserva_web.Add(oReserva);
                        db.SaveChanges();
                    }
                    return Redirect("~/Reservas/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }


        public ActionResult Editar(int idactualiza)
        {
            Listareservaweb model = new Listareservaweb();

            using (Context db = new Context())
            {
                var oReserva = db.Reserva_web.Find(idactualiza);
                model.fecha = oReserva.fecha;
                model.horainicio = oReserva.hora_inicio;
                model.cantidadminutos = oReserva.cantidad_minutos;
                model.horafin = oReserva.hora_fin;
                model.costo = oReserva.costo;
                model.idlineatiro = oReserva.id_linea_tiro;
            }
            return View(model);
        }


        [HttpPost]
        public ActionResult Editar(Listareservaweb model)
        {

            if (ModelState.IsValid)
            {
                using (Context db = new Context())
                {
                    var oReserva = db.Reserva_web.Find(model.Idactualiza);
                    oReserva.fecha = model.fecha;
                    oReserva.hora_inicio = model.horainicio;
                    oReserva.cantidad_minutos = model.cantidadminutos;
                    oReserva.hora_fin = model.horafin;
                    oReserva.costo = model.costo;
                    oReserva.id_linea_tiro = model.idlineatiroact;

                    db.Entry(oReserva).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
                return Redirect("~/Reservas/");
            }
            return View(model);

        }

        [HttpGet]
        public ActionResult Eliminar(int idelimina)
        {
            using (Context db = new Context())
            {
                var oReserva = db.Reserva_web.Find(idelimina);
                db.Reserva_web.Remove(oReserva);
                db.SaveChanges();
            }
            return Redirect("~/Reservas/");
        }


    }
}

poligonotiro/Controllers/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using poligonotiro.Models;
using poligonotiro.Models.ViewModels;

namespace poligonotiro.Controllers
{
    [Authorize]
    public class RolController : Controller
    {
        // GET: Rol
        public ActionResult Index()
        {
            int varrol = MySession.Current.Rol;

            if (varrol == 2)
            {
                return Redirect("~/Profile/");
            }
            else
            {
                List<ListaRoles> lst;

                using (Context db = new Context())

                {
                    lst = (from d in db.Rol
                           select new ListaRoles
                           {
                               Id = d.idrol,
                               descripcion = d.descripcion
                           }).ToList();
                }

                return View(lst);
            }

        }


        public ActionResult Nuevo()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Nuevo(InsertRol model)
        {
            try
            {
                if (ModelState.IsValid)
                {


                    using (Context db = new Context())

                    {
                        var oRol = new rol();
                        oRol.descripcion = model.descripcion;

                        db.Rol.Add(oRol);
                        db.SaveChanges();
                    }
                    return Redirect("~/Rol/");
                }
                return View(model);
                //return Redirect("/Rol");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

    }
}

poligonotiro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @if (User.Identity.IsAuthenticated)
    {
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Polígono de Tiro", "Index", "Profile", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">


                        @if (Session["IDROL"] == null)
                        {
                            FormsAuthentication.SignOut();
                            Response.Redirect("~/");
                        }
                        else
                        {
                            if ((int)Session["IDROL"] == 1)
                            {
                                <li>@Html.ActionLink("Armas", "", "Armas")</li>
                                <li>@Html.ActionLink("Clientes", "", "Clientes")</li>
                                <li>@Html.ActionLink("Lineas de tiro", "", "LineaTiro")</li>
                                <li>@Html.ActionLink("Reservas Web", "", "Reservas")</li>
                                <li>@Html.ActionLink("Temporizador de línea", "", "Temporizador")</li>
                                <li>@Html.ActionLink("Supervisores", "", "Supervisores")</li>
                                <li>@Html.ActionLink("Usuarios", "", "Usuarios")</li>
                                <li href="" data-toggle="modal" data-target="#parametrosdia"><a href="#">Reportes</a></li>

                                

                                <!--<li>@Html.ActionLink("Roles", "", "Rol")</li>-->

                                <li><a href="/Home/Logout">Cerrar Sesión</a></li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("Reservas Web", "", "ReservasUsuario")</li>
                                <li><a href="/Home/Logout">Cerrar Sesión</a></li>
                            }

                        }
                    </ul>
                </div>
            </div>
        </div>
    }


    <div class="modal fade" id="parametrosdia" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ingrese fechas</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    @using (Html.BeginForm("Index", "Reportedia", FormMethod.Get))
                    {

                        <div class="row">
                            <center>
                                <div class="col col-md-12">
                                    <label for="my-input">Fecha Inicio:</label>
                                    <input type="date" name="fechaini" class="form-control" placeholder="Fecha ini">
                                </div>
                                <br /><br /><br />
                                <br />
                                <div class="col col-md-12">
                                    <label for="my-input">Fecha Fin:</label>
                                    <input type="date" name="fechafin" class="form-control" placeholder="Fecha fin">
                                </div>
                            </center>
                        </div>

                        <br />

                        <div class="row" style="text-align: center;">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                            <input type="submit" value="Aceptar" class="btn btn-primary" />
                        </div>

                    }

                </div>

                <div class="modal-footer">

                </div>

            </div>
        </div>
    </div>

    <div class="modal fade" id="parametrosemana" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ingrese fechas de la semana</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    @using (Html.BeginForm("Index", "Reportesemana", FormMethod.Get))
                    {

                        <div class="row">
                            <center>
                                <div class="col col-md-12">
                                    <label for="my-input">Fecha Inicio:</label>
                                    <input type="date" name="fechaini" class="form-control" placeholder="Fecha ini">
                                </div>
                                <br /><br /><br />
                                <br />
                                <div class="col col-md-12">
                                    <label for="my-input">Fecha Fin:</label>
                                    <input type="date" name="fechafin" class="form-control" placeholder="Fecha fin">
                                </div>
                            </center>
                        </div>

                        <br />

                        <div class="row" style="text-align: center;">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                            <input type="submit" value="Aceptar" class="btn btn-primary" />
                        </div>

                    }

                </div>

                <div class="modal-footer">

                </div>

            </div>
        </div>
    </div>

    <div class="modal fade" id="parametromes" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ingrese fechas del mes</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    @using (Html.BeginForm("Index", "Reportemes", FormMethod.Get))
                    {

                        <div class="row">
                            <center>
                                <div class="col col-md-12">
                                    <label for="my-input">Fecha Inicio:</label>
                                    <input type="date" name="fechaini" class="form-control" placeholder="Fecha ini">
                                </div>
                                <br /><br /><br />
                                <br />
                                <div class="col col-md-12">
                                    <label for="my-input">Fecha Fin:</label>
                                    <input type="date" name="fechafin" class="form-control" placeholder="Fecha fin">
                                </div>
                            </center>
                        </div>

                        <br />

                        <div class="row" style="text-align: center;">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                            <input type="submit" value="Aceptar" class="btn btn-primary" />
                        </div>

                    }

                </div>

                <div class="modal-footer">

                </div>

            </div>
        </div>
    </div>


    <br /><br />
    <div class="container body-content">
        @RenderBody()
        <!--<hr />-->
        <footer>
            <p>&copy; @DateTime.Now.Year - Por B.G.S.P.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>