poligonotiro/Controllers/TemporizadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using poligonotiro.Models;
using poligonotiro.Models.ViewModels;

namespace poligonotiro.Controllers
{
    [Authorize]
    public class TemporizadorController : Controller
    {
        // GET: Temporizador
        public ActionResult Index()
        {
            int varrol = MySession.Current.Rol;

            if (varrol == 2)
            {
                return Redirect("~/Profile/");
            }
            else
            {
                List<ListaTemporizador> lst;
                using (Context db = new Context())
                {
                    lst = (from d in db.Temporizador_linea
                           select new ListaTemporizador
                           {
                               Id = d.id_temporizador,
                               idreserva = d.id_reserva_web
                           }).ToList();
                }


                //DROPDOWN DE RESERVAS

                List<Listareservaweb> lst1;
                using (Context db1 = new Context())
                {
                    lst1 = (from d1 in db1.Reserva_web
                            join t in db1.Usuario on d1.id_usuario equals t.id_usuario
                            select new Listareservaweb
                            {
                                Id = d1.id_reserva_web,
                                nombreusuario = t.nombre_usuario,
                                fecha = d1.fecha
                            }).ToList();
                }

                List<SelectListItem> items = lst1.ConvertAll(d1 =>
                {
                    return new SelectListItem()
                    {
                        Text = d1.Id.ToString() + " - " + d1.nombreusuario.ToString() + " - " + d1.fecha.ToShortDateString(),
                        Value = d1.Id.ToString(),
                        Selected = false
                    };
                });

                ViewBag.items = items;

                return View(lst);
            }
        }


        public ActionResult Nuevo()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Nuevo(ListaTemporizador model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (Context db = new Context())
                    {
                        var oTemporizador = new temporizador_linea();
                        oTemporizador.id_temporizador = model.Id;
                        oTemporizador.id_reserva_web = model.idreserva;

                        db.Temporizador_linea.Add(oTemporizador);
                        db.SaveChanges();
                    }
                    return Redirect("~/Temporizador/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }


        public ActionResult Editar(int idactualiza)
        {
            ListaTemporizador model = new ListaTemporizador();

            using (Context db = new Context())
            {
                var oReserva = db.Temporizador_linea.Find(idactualiza);
                model.idreserva = oReserva.id_reserva_web;
            }
            return View(model);
        }


        [HttpPost]
        public ActionResult Editar(ListaTemporizador model)
        {

            if (ModelState.IsValid)
            {
                using (Context db = new Context())
                {
                    var oTemporizador = db.Temporizador_linea.Find(model.idactualiza);
                    oTemporizador.id_reserva_web = model.idreservaact;

                    db.Entry(oTemporizador).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
                return Redirect("~/Temporizador/");
            }
            return View(model);

        }

        [HttpGet]
        public ActionResult Eliminar(int idelimina)
        {
            using (Context db = new Context())
            {
                var oTemporizador = db.Temporizador_linea.Find(idelimina);
                db.Temporizador_linea.Remove(oTemporizador);
                db.SaveChanges();
            }
            return Redirect("~/Temporizador/");
        }


    }
}

poligonotiro/Views/Temporizador/Index.cshtml
@model List<poligonotiro.Models.ViewModels.ListaTemporizador>

@{
    ViewBag.Title = "Temporizador de Líneas";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
}
<body style="background: url(/Content/images/pol1.jpg); background-size: cover; background-position: center;">
    <h2>@ViewBag.Title</h2>

    <div class="row" style="text-align:right;padding:5px;">
        <a href="#" data-toggle="modal" data-target="#agregartemporizador" class="btn btn-primary">Nuevo</a>
    </div>

    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped" width="100%" border="3" cellspacing="10" cellpadding="10" style="background: white;">
                <tr>
                    <th width="33%">No. Temporizador</th>
                    <th width="33%">No. Reserva</th>
                    <th width="33%" style="text-align: center;">Acciones</th>
                </tr>
                @foreach (var oElemento in Model)
                {
                    <tr>
                        <td width="33%">@oElemento.Id </td>
                        <td width="33%">@oElemento.idreserva</td>
                        <td width="33%" align="center">
                            <a href="" data-toggle="modal" data-target="#editartemporizador" class="btn btn-warning" onclick="editartemporizador('@oElemento.Id','@oElemento.idreserva')">Editar</a>
                            <a href="" data-toggle="modal" data-target="#eliminartemporizador" class="btn btn-danger" onclick="eliminartemporizador('@oElemento.Id')">Eliminar</a>
                        </td>
                    </tr>
                }
            </table>
        </div>

    </div>

    <script type="text/javascript">
        function editartemporizador(id, idreserva) {
            $('#idactualiza').val(id);
            $('#idreservaact').val(idreserva);
    };

        function eliminartemporizador(id) {
            $('#idelimina').val(id);
        }
    </script>


    <div class="modal fade" id="agregartemporizador" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Agregar Temporizador</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    @using (Html.BeginForm("Nuevo", "Temporizador", FormMethod.Post))
                    {

                        <div class="row">
                            <center>
                                <div class="col col-md-12">
                                    <label for="my-input">No de Reserva:</label>
                                    @Html.DropDownList("idreserva", items, "Selecciona una reserva", new { @class = "form-control" })

                                </div>
                            </center>
                        </div>

                        <br />

                        <div class="row" style="text-align: center;">
                            <input type="submit" value="Guardar" class="btn btn-primary" />
                        </div>

                    }

                </div>

                <div class="modal-footer">

                </div>

            </div>
        </div>
    </div>


    <div class="modal fade" id="editartemporizador" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Editar Reservas</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    @using (Html.BeginForm("Editar", "Temporizador", FormMethod.Post))
                    {

                        <div class="row">
                            <center>
                                <input type="hidden" name="idactualiza" id="idactualiza" class="form-control" placeholder="ID" required="" readonly="">

                                <div class="col col-md-12">
                                    <label for="my-input">No de Reserva:</label>
                                    @Html.DropDownList("idreservaact", items, "Selecciona una reserva", new { @class = "form-control" })

                                </div>
                            </center>
                        </div>

                        <br />

                        <div class="row" style="text-align: center;">
                            <input type="submit" value="Guardar" class="btn btn-primary" />
                        </div>

                    }

                </div>

                <div class="modal-footer">

                </div>

            </div>
        </div>
    </div>


    <div class="modal fade" id="eliminartemporizador" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Eliminar Temporizador</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    @using (Html.BeginForm("Eliminar", "Temporizador", FormMethod.Get))
                    {

                        <div class="row">
                            <center>
                                <input type="hidden" name="idelimina" id="idelimina" class="form-control" placeholder="ID" required="" readonly="">

                                <h2>¿Está Seguro de eliminar el temporizador?</h2>
                            </center>
                        </div>

                        <br />

                        <div class="row" style="text-align: center;">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                            <input type="submit" value="Aceptar" class="btn btn-primary" />
                        </div>

                    }

                </div>

                <div class="modal-footer">

                </div>

            </div>
        </div>
    </div>
</body>